/** Nichos AmazFlash (alineados con web/src/data/niche-pages.ts). */
export const NICHES = [
  {
    slug: 'generales',
    emoji: '🛍️',
    name: 'Ofertas generales',
    channelUsername: 'amazflash',
    categoryAliases: ['general', 'generales', 'amazon'],
    minDiscount: 20,
  },
  {
    slug: 'juegos-ps5',
    emoji: '🎮',
    name: 'Gaming · PlayStation',
    channelUsername: 'amazflash_ps',
    categoryAliases: ['gaming_ps', 'gaming ps', 'playstation', 'ps5', 'ps4', 'ps'],
    minDiscount: 10,
    titlePattern: /\b(?:ps\s*5|ps5|play\s*5|play5|ps\s*4|ps4|play\s*4|play4|playstation|play\s*station|dualsense|dualshock|sony\s*ps)\b/i,
    excludeTitlePattern: /\b(?:nintendo|switch|xbox|joy[-\s]?con|amiibo)\b/i,
  },
  {
    slug: 'nintendo-switch',
    emoji: '🎮',
    name: 'Gaming · Nintendo Switch',
    channelUsername: 'amazflash_switch',
    categoryAliases: ['gaming_switch', 'gaming switch', 'switch', 'nintendo'],
    minDiscount: 10,
    titlePattern: /\b(?:nintendo\s*switch|switch\s*2|switch\s*oled|joy[-\s]?con|joycon|amiibo|nintendo)\b/i,
    excludeTitlePattern: /\b(?:ps[45]|playstation|xbox|dualsense)\b/i,
  },
  {
    slug: 'xbox',
    emoji: '🎮',
    name: 'Gaming · Xbox',
    channelUsername: 'amazflash_xbox',
    categoryAliases: ['gaming_xbox', 'gaming xbox', 'xbox'],
    minDiscount: 10,
    titlePattern: /\b(?:xbox|series\s*x|series\s*s|game\s*pass|gamepass)\b/i,
    excludeTitlePattern: /\b(?:ps[45]|playstation|nintendo|switch|dualsense)\b/i,
  },
  {
    slug: 'gaming-pc',
    emoji: '🎮',
    name: 'Gaming · PC',
    channelUsername: 'amazflash_pc',
    categoryAliases: ['gaming_pc', 'gaming pc', 'steam', 'epic', 'gog'],
    minDiscount: 10,
    titlePattern: /\b(?:steam|epic\s*games|gog|humble|gaming\s*pc|ratón\s*gaming|teclado\s*gaming)\b/i,
  },
  {
    slug: 'tecnologia',
    emoji: '💻',
    name: 'Tecnología',
    channelUsername: 'amazflash_tech',
    categoryAliases: ['tech', 'tecnologia', 'tecnología', 'electronica', 'electrónica', 'auriculares', 'camaras', 'cámaras'],
    minDiscount: 20,
  },
  {
    slug: 'hogar',
    emoji: '🏠',
    name: 'Hogar y cocina',
    channelUsername: 'amazflash_hogar',
    categoryAliases: ['hogar', 'cocina', 'alimentacion', 'electrodomesticos'],
    minDiscount: 20,
  },
  {
    slug: 'herramientas',
    emoji: '🛠️',
    name: 'Herramientas',
    channelUsername: 'amazflash_tools',
    categoryAliases: ['tools', 'herramientas', 'bricolaje', 'ferreteria', 'ferretería'],
    minDiscount: 20,
  },
  {
    slug: 'mascotas',
    emoji: '🐶',
    name: 'Mascotas',
    channelUsername: 'amazflash_mascotas',
    categoryAliases: ['mascotas', 'pets', 'perros', 'gatos'],
    minDiscount: 20,
  },
  {
    slug: 'belleza',
    emoji: '💄',
    name: 'Belleza',
    channelUsername: 'amazflash_belleza',
    categoryAliases: ['belleza', 'cosmetica', 'cosmética', 'perfumeria', 'perfumería'],
    minDiscount: 20,
  },
  {
    slug: 'bebes',
    emoji: '👶',
    name: 'Bebés y niños',
    channelUsername: 'amazflash_bebes',
    categoryAliases: ['bebes', 'bebés', 'bebe', 'bebé', 'infantil', 'niños'],
    minDiscount: 20,
  },
  {
    slug: 'deportes',
    emoji: '🏀',
    name: 'Deportes',
    channelUsername: 'amazflash_deportes',
    categoryAliases: ['deportes', 'fitness', 'running', 'gym'],
    minDiscount: 20,
  },
  {
    slug: 'juegos-mesa',
    emoji: '🎲',
    name: 'Juegos de mesa',
    channelUsername: 'amazflash_juegosmesa',
    categoryAliases: ['juegos_mesa', 'juegos mesa', 'board games', 'tablero'],
    minDiscount: 20,
  },
  {
    slug: 'verano',
    emoji: '🌞',
    name: 'Verano',
    channelUsername: 'amazflash_summer',
    categoryAliases: ['summer', 'verano', 'piscina', 'playa'],
    minDiscount: 20,
    titlePattern: /\b(?:piscina|ventilador|hamaca|parasol|playa|verano)\b/i,
  },
  {
    slug: 'outdoor',
    emoji: '🏕️',
    name: 'Outdoor / survival',
    channelUsername: 'amazflash_survival',
    categoryAliases: ['survival', 'outdoor', 'camping', 'cámping'],
    minDiscount: 20,
    titlePattern: /\b(?:camping|cámping|survival|linterna|navaja|multiherramienta|edc)\b/i,
  },
  {
    slug: 'moda-hombre',
    emoji: '👔',
    name: 'Moda hombre',
    channelUsername: 'amazflash_modah',
    categoryAliases: ['moda_h', 'moda hombre', 'moda-hombre'],
    minDiscount: 20,
  },
  {
    slug: 'moda-mujer',
    emoji: '👗',
    name: 'Moda mujer',
    channelUsername: 'amazflash_modam',
    categoryAliases: ['moda_m', 'moda mujer', 'moda-mujer'],
    minDiscount: 20,
  },
];

export const NICHES_BY_SLUG = Object.fromEntries(NICHES.map((n) => [n.slug, n]));

export const DEFAULT_NICHES = [
  'generales',
  'tecnologia',
  'gaming-pc',
  'juegos-ps5',
  'nintendo-switch',
  'hogar',
];
